### PR TITLE
IHCIC-45 Updating the password handling, so that we do not add the

### PR DESCRIPTION
**Pull request by psantos1113**
--password option if the Hub is 3.1.0 or newer

### CODE REVIEW

**Comment by psantos1113** [comment]
@jrichardBD @ekerwin @akamen @stevebillings  please review in order to get this merged into the next version of hub common.

**Comment by stevebillings** [comment]
Looks good

**Comment by ekerwin** [comment]
Looks good

**Comment by jrichardBD** [comment]
Looks good to me

**Pull request merged**
