### PR TITLE
Getting policy rules

### PR DESCRIPTION
**Pull request by jrichardBD**
@ekerwin @psantos1113 @akamen @stevebillings  please review this PR

### CODE REVIEW

**Comment by stevebillings** [comment]
Looks good.

**Comment by jrichardBD** [comment]
@stevebillings Please review again with the new changes

**Comment by stevebillings** [comment]
Looks even gooder.

**Comment by jrichardBD** [comment]
@stevebillings @ekerwin @psantos1113 @akamen  Ignore this PR, I have more changes to make. Sorry for the waste of time :(

**Pull request closed without merging**
