### PR TITLE
Setting the credentials are part of the POST body and not in the URL

### PR DESCRIPTION
**Pull request by jrichardBD**

### CODE REVIEW

**Comment by jrichardBD** [comment]
@psantos1113  @ekerwin  Please review this PR when you have a chance

**Comment by ekerwin** [comment]
I love it.

**Comment by psantos1113** [comment]
looks good

**Comment by akamen** [comment]
Great job James!   Definitely felt uneasy appending such data to URL.   What is the impact from a security standpoint?   Will no longer show up in access logs because the body is not logged, right?

**Comment by jrichardBD** [comment]
Exactly, access logs will no longer contain credentials in clear text

**Pull request merged**
