### PR TITLE
32: added HubItem.getLinks()

### PR DESCRIPTION
**Pull request by stevebillings**
@jrichardBD @ekerwin @akamen @psantos1113 I ran into the need for a new method on HubItem. Please review...

### CODE REVIEW

**Comment by stevebillings** [comment]
@jrichardBD @ekerwin @akamen @psantos1113 Retracting this pr for some re-work.

**Comment by stevebillings** [comment]
@ekerwin @akamen @jrichardBD @psantos1113 : Replaced AbstractLinkedResource with HubItem. Eliminated HubItem.getLink(). Where getLink() had been used, throw exception of #links returned is not 1. Ready for review.

**Comment by ekerwin** [comment]
Looks good to me.

**Comment by jrichardBD** [comment]
Looks great Steve

**Comment by psantos1113** [comment]
Looks good

**Comment by akamen** [comment]
Looks nice!

**Pull request merged**
