### PR TITLE
Api user notification

### PR DESCRIPTION
**Pull request by psantos1113**
@stevebillings @ekerwin @jrichardBD  Please review these are the changes for user notifications.

### CODE REVIEW

**Comment by stevebillings** [comment]
Looks good.

**Comment by ekerwin** [comment]
It'd be great if the date format stuff didn't leak out, but that's a fix we can address later.

**Comment by ekerwin** [comment]
Love it.

**Comment by psantos1113** [comment]
We'll have to add the start and end dates as members of the item request and encapsulate the date format and query parameters as something to go forward.

**Pull request merged**
